[package]
name = "dm-maker"
version = "0.1.0"
edition = "2021"

[dependencies]
las = { version = "0.9.3", features = ["laz-parallel"] }
proj = "0.28.0"
rayon = "1.10.0"
rusqlite = "0.32.1"
startin = "0.8.2"
tiff = "0.9.1"
walkdir = "2.5.0"
