[package]
name = "lazindex"
version = "0.1.0"
edition = "2024"

[dependencies]
las = { version = "0.9.3", features = ["laz-parallel"] }
rusqlite = "0.34.0"
walkdir = "2.5.0"
clap = { version = "4.5.32", features = ["derive"] }

[profile.release]
panic = "abort"
