[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }
axum = "0.8.4"
rusqlite = "0.36.0"
hyper = "1.6.0"
clap = { version = "4.5.40", features = ["derive"] }
